<a href="https://colab.research.google.com/github/deliciousushi/MultipleDiseasePrediction/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
from sklearn.impute import SimpleImputer
from sklearn import preprocessing

In [49]:
df=pd.read_csv("kidney_disease.csv")

In [50]:
df.shape

(400, 26)

In [51]:
df.columns

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [52]:
df.isnull().sum().sort_values(ascending=True)

id                  0
classification      0
appet               1
ane                 1
pe                  1
htn                 2
cad                 2
dm                  2
ba                  4
pcc                 4
age                 9
bp                 12
sc                 17
bu                 19
bgr                44
al                 46
sg                 47
su                 49
hemo               52
pc                 65
pcv                70
sod                87
pot                88
wc                105
rc                130
rbc               152
dtype: int64

In [53]:
for col in df.columns:
    print(f"Unique values in {col}: {df[col].unique()}\n")

Unique values in id: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399]

Unique values in age: [48.  7. 62. 51. 60. 68. 24. 52. 53. 50. 63. 40. 47. 61. 21. 42. 75. 69.
 nan 73. 70. 65. 76. 72. 82. 46. 45. 35. 54. 11. 59. 67. 15. 55. 44. 26.
 64. 56.  5. 74. 38. 58. 71. 34. 17. 12. 43. 41. 57.  8. 39. 66. 81. 14.
 27. 83. 30.  4.  3.  6. 32. 80. 49. 90. 78. 19.  2. 33. 36. 37. 23. 25.
 20. 29. 28. 22. 79.]

Unique values in bp: [ 80.  50.  70.  90.  nan 100.  60. 110. 140. 180. 120.]

Unique values in sg: [1.02  1.01  1.005 1.015   nan 1.025]

Unique values in al: [ 1.  4.  2.  3.  0. nan  5.]

Unique values in su: [ 0.  3.  4.  1. nan  2.  5.]

Unique values in rbc: [nan 'normal' 'abnormal']

Unique values in pc: ['normal' 'abnormal' nan]

Unique values in pcc: ['notpresent' 'present' nan]

Unique values in ba: ['notpresent' 'present' nan]

Unique values in bgr: [121.  nan 423. 117. 106.  74. 100. 410. 138.  70. 490. 380. 208.  98.
 157.  76.  99. 114. 263. 173.  95. 108. 156. 264. 123.  93. 107. 159.
 140. 171. 270.  92. 137. 204.  79. 207. 124. 144.  91. 162. 246. 253.
 141. 182.  86. 150. 146. 425. 112. 250. 360. 163. 129. 133. 102. 158.
 165. 132. 104. 127. 415. 169. 251. 109. 280. 210. 219. 295.  94. 172.
 101. 298. 153.  88. 226. 143. 115.  89. 297. 233. 294. 323. 125.  90.
 308. 118. 224. 128. 122. 214. 213. 268. 256.  84. 105. 288. 139.  78.
 273. 242. 424. 303. 148. 160. 192. 307. 220. 447. 309.  22. 111. 261.
 215. 234. 131. 352.  80. 239. 110. 130. 184. 252. 113. 230. 341. 255.
 103. 238. 248. 120. 241. 269. 201. 203. 463. 176.  82. 119.  97.  96.
  81. 116. 134.  85.  83.  87.  75.]

Unique values in bu: [ 36.   18.   53.   56.   26.   25.   54.   31.   60.  107.   55.   72.
  86.   90.  162.   46.   87.   27.  148.  180.  163.    nan  50.   75.
  45.   28.  155.   33.   39.  153.   29.   65.  103.   70.   80.   20.
 202.   77.   89.   24.   17.   32.  114.   66.   38.  164.  142.   96.
 391.   15.  111.   73.   19.   92.   35.   16.  139.   48.   85.   98.
 186.   37.   47.   52.   82.   51.  106.   22.  217.   88.  118.   50.1
  71.   34.   40.   21.  219.   30.  125.  166.   49.  208.  176.   68.
 145.  165.  322.   23.  235.  132.   76.   42.   44.   41.  113.    1.5
 146.   58.  133.  137.   67.  115.  223.   98.6 158.   94.   74.  150.
  61.   57.   95.  191.   93.  241.   64.   79.  215.  309.   10. ]

Unique values in sc: [ 1.2   0.8   1.8   3.8   1.4   1.1  24.    1.9   7.2   4.    2.7   2.1
  4.6   4.1   9.6   2.2   5.2   1.3   1.6   3.9  76.    7.7    nan  2.4
  7.3   1.5   2.5   2.    3.4   0.7   1.   10.8   6.3   5.9   0.9   3.
  3.25  9.7   6.4   3.2  32.    0.6   6.1   3.3   6.7   8.5   2.8  15.
  2.9   1.7   3.6   5.6   6.5   4.4  10.2  11.5   0.5  12.2   5.3   9.2
 13.8  16.9   6.    7.1  18.    2.3  13.   48.1  14.2  16.4   2.6   7.5
  4.3  18.1  11.8   9.3   6.8  13.5  12.8  11.9  12.   13.4  15.2  13.3
  0.4 ]

Unique values in sod: [  nan 111.  142.  104.  114.  131.  138.  135.  130.  141.  139.    4.5
 136.  129.  140.  132.  133.  134.  125.  163.  137.  128.  143.  127.
 146.  126.  122.  147.  124.  115.  145.  113.  120.  150.  144. ]

Unique values in pot: [ nan  2.5  3.2  4.   3.7  4.2  5.8  3.4  6.4  4.9  4.1  4.3  5.2  3.8
  4.6  3.9  4.7  5.9  4.8  4.4  6.6 39.   5.5  5.   3.5  3.6  7.6  2.9
  4.5  5.7  5.4  5.3 47.   6.3  5.1  5.6  3.   2.8  2.7  6.5  3.3]

Unique values in hemo: [15.4 11.3  9.6 11.2 11.6 12.2 12.4 10.8  9.5  9.4  9.7  9.8  5.6  7.6
 12.6 12.1 12.7 10.3  7.7 10.9  nan 11.1  9.9 12.5 12.9 10.1 12.  13.
  7.9  9.3 15.  10.   8.6 13.6 10.2 10.5  6.6 11.   7.5 15.6 15.2  4.8
  9.1  8.1 11.9 13.5  8.3  7.1 16.1 10.4  9.2  6.2 13.9 14.1  6.  11.8
 11.7 11.4 14.   8.2 13.2  6.1  8.  12.3  8.4 14.3  9.   8.7 10.6 13.1
 10.7  5.5  5.8  6.8  8.8  8.5 13.8 11.5  7.3 13.7 12.8 13.4  6.3  3.1
 17.  15.9 14.5 15.5 16.2 14.4 14.2 16.3 14.8 16.5 15.7 13.3 14.6 16.4
 16.9 16.  14.7 16.6 14.9 16.7 16.8 15.8 15.1 17.1 17.2 15.3 17.3 17.4
 17.7 17.8 17.5 17.6]

Unique values in pcv: ['44' '38' '31' '32' '35' '39' '36' '33' '29' '28' nan '16' '24' '37' '30'
 '34' '40' '45' '27' '48' '\t?' '52' '14' '22' '18' '42' '17' '46' '23'
 '19' '25' '41' '26' '15' '21' '43' '20' '\t43' '47' '9' '49' '50' '53'
 '51' '54']

Unique values in wc: ['7800' '6000' '7500' '6700' '7300' nan '6900' '9600' '12100' '4500'
 '12200' '11000' '3800' '11400' '5300' '9200' '6200' '8300' '8400' '10300'
 '9800' '9100' '7900' '6400' '8600' '18900' '21600' '4300' '8500' '11300'
 '7200' '7700' '14600' '6300' '\t6200' '7100' '11800' '9400' '5500' '5800'
 '13200' '12500' '5600' '7000' '11900' '10400' '10700' '12700' '6800'
 '6500' '13600' '10200' '9000' '14900' '8200' '15200' '5000' '16300'
 '12400' '\t8400' '10500' '4200' '4700' '10900' '8100' '9500' '2200'
 '12800' '11200' '19100' '\t?' '12300' '16700' '2600' '26400' '8800'
 '7400' '4900' '8000' '12000' '15700' '4100' '5700' '11500' '5400' '10800'
 '9900' '5200' '5900' '9300' '9700' '5100' '6600']

Unique values in rc: ['5.2' nan '3.9' '4.6' '4.4' '5' '4.0' '3.7' '3.8' '3.4' '2.6' '2.8' '4.3'
 '3.2' '3.6' '4' '4.1' '4.9' '2.5' '4.2' '4.5' '3.1' '4.7' '3.5' '6.0'
 '5.0' '2.1' '5.6' '2.3' '2.9' '2.7' '8.0' '3.3' '3.0' '3' '2.4' '4.8'
 '\t?' '5.4' '6.1' '6.2' '6.3' '5.1' '5.8' '5.5' '5.3' '6.4' '5.7' '5.9'
 '6.5']

Unique values in htn: ['yes' 'no' nan]

Unique values in dm: ['yes' 'no' ' yes' '\tno' '\tyes' nan]

Unique values in cad: ['no' 'yes' '\tno' nan]

Unique values in appet: ['good' 'poor' nan]

Unique values in pe: ['no' 'yes' nan]

Unique values in ane: ['no' 'yes' nan]

Unique values in classification: ['ckd' 'ckd\t' 'notckd']

In [54]:
# Define numerical and categorical columns
numerical_columns = ['age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc']
categorical_columns = ['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane' ,'classification']

# Convert problematic values to NaN
df[numerical_columns] = df[numerical_columns].replace(['\t?', '?'], np.nan)
df[numerical_columns] = df[numerical_columns].apply(pd.to_numeric, errors='coerce')

# Apply imputation
num_imputer = SimpleImputer(strategy="median")
df[numerical_columns] = num_imputer.fit_transform(df[numerical_columns])

cat_imputer = SimpleImputer(strategy="most_frequent")
df[categorical_columns] = cat_imputer.fit_transform(df[categorical_columns])

In [55]:
df[categorical_columns] = df[categorical_columns].apply(lambda x: x.str.strip())
df['dm'] = df['dm'].replace({'\tyes': 'yes', '\tno': 'no'})
df['cad'] = df['cad'].replace({'\tno': 'no'})
df['classification'] = df['classification'].replace({'ckd\t': 'ckd'})

In [56]:
mode=SimpleImputer(missing_values = np.nan , strategy = "most_frequent")
df_clean=pd.DataFrame(mode.fit_transform(df))
df_clean.columns=df.columns
df_clean

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.02,1.0,0.0,normal,normal,notpresent,notpresent,...,44.0,7800.0,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.02,4.0,0.0,normal,normal,notpresent,notpresent,...,38.0,6000.0,4.8,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.01,2.0,3.0,normal,normal,notpresent,notpresent,...,31.0,7500.0,4.8,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.01,2.0,0.0,normal,normal,notpresent,notpresent,...,35.0,7300.0,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.02,0.0,0.0,normal,normal,notpresent,notpresent,...,47.0,6700.0,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54.0,7800.0,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.02,0.0,0.0,normal,normal,notpresent,notpresent,...,49.0,6600.0,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51.0,7200.0,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53.0,6800.0,6.1,no,no,no,good,no,no,notckd

In [57]:
for col in df_clean.columns:
    print(f"Unique values in {col}: {df_clean[col].unique()}\n")

Unique values in id: [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51
 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75
 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99
 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207
 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225
 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243
 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261
 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279
 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297
 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315
 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333
 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351
 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369
 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386 387
 388 389 390 391 392 393 394 395 396 397 398 399]

Unique values in age: [48.0 7.0 62.0 51.0 60.0 68.0 24.0 52.0 53.0 50.0 63.0 40.0 47.0 61.0 21.0
 42.0 75.0 69.0 55.0 73.0 70.0 65.0 76.0 72.0 82.0 46.0 45.0 35.0 54.0
 11.0 59.0 67.0 15.0 44.0 26.0 64.0 56.0 5.0 74.0 38.0 58.0 71.0 34.0 17.0
 12.0 43.0 41.0 57.0 8.0 39.0 66.0 81.0 14.0 27.0 83.0 30.0 4.0 3.0 6.0
 32.0 80.0 49.0 90.0 78.0 19.0 2.0 33.0 36.0 37.0 23.0 25.0 20.0 29.0 28.0
 22.0 79.0]

Unique values in bp: [80.0 50.0 70.0 90.0 100.0 60.0 110.0 140.0 180.0 120.0]

Unique values in sg: [1.02 1.01 1.005 1.015 1.025]

Unique values in al: [1.0 4.0 2.0 3.0 0.0 5.0]

Unique values in su: [0.0 3.0 4.0 1.0 2.0 5.0]

Unique values in rbc: ['normal' 'abnormal']

Unique values in pc: ['normal' 'abnormal']

Unique values in pcc: ['notpresent' 'present']

Unique values in ba: ['notpresent' 'present']

Unique values in bgr: [121.0 423.0 117.0 106.0 74.0 100.0 410.0 138.0 70.0 490.0 380.0 208.0
 98.0 157.0 76.0 99.0 114.0 263.0 173.0 95.0 108.0 156.0 264.0 123.0 93.0
 107.0 159.0 140.0 171.0 270.0 92.0 137.0 204.0 79.0 207.0 124.0 144.0
 91.0 162.0 246.0 253.0 141.0 182.0 86.0 150.0 146.0 425.0 112.0 250.0
 360.0 163.0 129.0 133.0 102.0 158.0 165.0 132.0 104.0 127.0 415.0 169.0
 251.0 109.0 280.0 210.0 219.0 295.0 94.0 172.0 101.0 298.0 153.0 88.0
 226.0 143.0 115.0 89.0 297.0 233.0 294.0 323.0 125.0 90.0 308.0 118.0
 224.0 128.0 122.0 214.0 213.0 268.0 256.0 84.0 105.0 288.0 139.0 78.0
 273.0 242.0 424.0 303.0 148.0 160.0 192.0 307.0 220.0 447.0 309.0 22.0
 111.0 261.0 215.0 234.0 131.0 352.0 80.0 239.0 110.0 130.0 184.0 252.0
 113.0 230.0 341.0 255.0 103.0 238.0 248.0 120.0 241.0 269.0 201.0 203.0
 463.0 176.0 82.0 119.0 97.0 96.0 81.0 116.0 134.0 85.0 83.0 87.0 75.0]

Unique values in bu: [36.0 18.0 53.0 56.0 26.0 25.0 54.0 31.0 60.0 107.0 55.0 72.0 86.0 90.0
 162.0 46.0 87.0 27.0 148.0 180.0 163.0 42.0 50.0 75.0 45.0 28.0 155.0
 33.0 39.0 153.0 29.0 65.0 103.0 70.0 80.0 20.0 202.0 77.0 89.0 24.0 17.0
 32.0 114.0 66.0 38.0 164.0 142.0 96.0 391.0 15.0 111.0 73.0 19.0 92.0
 35.0 16.0 139.0 48.0 85.0 98.0 186.0 37.0 47.0 52.0 82.0 51.0 106.0 22.0
 217.0 88.0 118.0 50.1 71.0 34.0 40.0 21.0 219.0 30.0 125.0 166.0 49.0
 208.0 176.0 68.0 145.0 165.0 322.0 23.0 235.0 132.0 76.0 44.0 41.0 113.0
 1.5 146.0 58.0 133.0 137.0 67.0 115.0 223.0 98.6 158.0 94.0 74.0 150.0
 61.0 57.0 95.0 191.0 93.0 241.0 64.0 79.0 215.0 309.0 10.0]

Unique values in sc: [1.2 0.8 1.8 3.8 1.4 1.1 24.0 1.9 7.2 4.0 2.7 2.1 4.6 4.1 9.6 2.2 5.2 1.3
 1.6 3.9 76.0 7.7 2.4 7.3 1.5 2.5 2.0 3.4 0.7 1.0 10.8 6.3 5.9 0.9 3.0
 3.25 9.7 6.4 3.2 32.0 0.6 6.1 3.3 6.7 8.5 2.8 15.0 2.9 1.7 3.6 5.6 6.5
 4.4 10.2 11.5 0.5 12.2 5.3 9.2 13.8 16.9 6.0 7.1 18.0 2.3 13.0 48.1 14.2
 16.4 2.6 7.5 4.3 18.1 11.8 9.3 6.8 13.5 12.8 11.9 12.0 13.4 15.2 13.3 0.4]

Unique values in sod: [138.0 111.0 142.0 104.0 114.0 131.0 135.0 130.0 141.0 139.0 4.5 136.0
 129.0 140.0 132.0 133.0 134.0 125.0 163.0 137.0 128.0 143.0 127.0 146.0
 126.0 122.0 147.0 124.0 115.0 145.0 113.0 120.0 150.0 144.0]

Unique values in pot: [4.4 2.5 3.2 4.0 3.7 4.2 5.8 3.4 6.4 4.9 4.1 4.3 5.2 3.8 4.6 3.9 4.7 5.9
 4.8 6.6 39.0 5.5 5.0 3.5 3.6 7.6 2.9 4.5 5.7 5.4 5.3 47.0 6.3 5.1 5.6 3.0
 2.8 2.7 6.5 3.3]

Unique values in hemo: [15.4 11.3 9.6 11.2 11.6 12.2 12.4 10.8 9.5 9.4 9.7 9.8 5.6 7.6 12.6 12.1
 12.7 10.3 7.7 10.9 12.649999999999999 11.1 9.9 12.5 12.9 10.1 12.0 13.0
 7.9 9.3 15.0 10.0 8.6 13.6 10.2 10.5 6.6 11.0 7.5 15.6 15.2 4.8 9.1 8.1
 11.9 13.5 8.3 7.1 16.1 10.4 9.2 6.2 13.9 14.1 6.0 11.8 11.7 11.4 14.0 8.2
 13.2 6.1 8.0 12.3 8.4 14.3 9.0 8.7 10.6 13.1 10.7 5.5 5.8 6.8 8.8 8.5
 13.8 11.5 7.3 13.7 12.8 13.4 6.3 3.1 17.0 15.9 14.5 15.5 16.2 14.4 14.2
 16.3 14.8 16.5 15.7 13.3 14.6 16.4 16.9 16.0 14.7 16.6 14.9 16.7 16.8
 15.8 15.1 17.1 17.2 15.3 17.3 17.4 17.7 17.8 17.5 17.6]

Unique values in pcv: [44.0 38.0 31.0 32.0 35.0 39.0 36.0 33.0 29.0 28.0 40.0 16.0 24.0 37.0
 30.0 34.0 45.0 27.0 48.0 52.0 14.0 22.0 18.0 42.0 17.0 46.0 23.0 19.0
 25.0 41.0 26.0 15.0 21.0 43.0 20.0 47.0 9.0 49.0 50.0 53.0 51.0 54.0]

Unique values in wc: [7800.0 6000.0 7500.0 6700.0 7300.0 8000.0 6900.0 9600.0 12100.0 4500.0
 12200.0 11000.0 3800.0 11400.0 5300.0 9200.0 6200.0 8300.0 8400.0 10300.0
 9800.0 9100.0 7900.0 6400.0 8600.0 18900.0 21600.0 4300.0 8500.0 11300.0
 7200.0 7700.0 14600.0 6300.0 7100.0 11800.0 9400.0 5500.0 5800.0 13200.0
 12500.0 5600.0 7000.0 11900.0 10400.0 10700.0 12700.0 6800.0 6500.0
 13600.0 10200.0 9000.0 14900.0 8200.0 15200.0 5000.0 16300.0 12400.0
 10500.0 4200.0 4700.0 10900.0 8100.0 9500.0 2200.0 12800.0 11200.0
 19100.0 12300.0 16700.0 2600.0 26400.0 8800.0 7400.0 4900.0 12000.0
 15700.0 4100.0 5700.0 11500.0 5400.0 10800.0 9900.0 5200.0 5900.0 9300.0
 9700.0 5100.0 6600.0]

Unique values in rc: [5.2 4.8 3.9 4.6 4.4 5.0 4.0 3.7 3.8 3.4 2.6 2.8 4.3 3.2 3.6 4.1 4.9 2.5
 4.2 4.5 3.1 4.7 3.5 6.0 2.1 5.6 2.3 2.9 2.7 8.0 3.3 3.0 2.4 5.4 6.1 6.2
 6.3 5.1 5.8 5.5 5.3 6.4 5.7 5.9 6.5]

Unique values in htn: ['yes' 'no']

Unique values in dm: ['yes' 'no']

Unique values in cad: ['no' 'yes']

Unique values in appet: ['good' 'poor']

Unique values in pe: ['no' 'yes']

Unique values in ane: ['no' 'yes']

Unique values in classification: ['ckd' 'notckd']

In [58]:
from sklearn.preprocessing import LabelEncoder
label_encoders = {}
for col in categorical_columns:
    le = LabelEncoder()
    df_clean[col] = le.fit_transform(df_clean[col])
    label_encoders[col] = le
df_clean

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.02,1.0,0.0,1,1,0,0,...,44.0,7800.0,5.2,1,1,0,0,0,0,0
1,1,7.0,50.0,1.02,4.0,0.0,1,1,0,0,...,38.0,6000.0,4.8,0,0,0,0,0,0,0
2,2,62.0,80.0,1.01,2.0,3.0,1,1,0,0,...,31.0,7500.0,4.8,0,1,0,1,0,1,0
3,3,48.0,70.0,1.005,4.0,0.0,1,0,1,0,...,32.0,6700.0,3.9,1,0,0,1,1,1,0
4,4,51.0,80.0,1.01,2.0,0.0,1,1,0,0,...,35.0,7300.0,4.6,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.02,0.0,0.0,1,1,0,0,...,47.0,6700.0,4.9,0,0,0,0,0,0,1
396,396,42.0,70.0,1.025,0.0,0.0,1,1,0,0,...,54.0,7800.0,6.2,0,0,0,0,0,0,1
397,397,12.0,80.0,1.02,0.0,0.0,1,1,0,0,...,49.0,6600.0,5.4,0,0,0,0,0,0,1
398,398,17.0,60.0,1.025,0.0,0.0,1,1,0,0,...,51.0,7200.0,5.9,0,0,0,0,0,0,1
399,399,58.0,80.0,1.025,0.0,0.0,1,1,0,0,...,53.0,6800.0,6.1,0,0,0,0,0,0,1

In [59]:
df_clean.describe()

,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane,classification
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.00000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,0.882500,0.810000,0.105000,0.055000,0.367500,0.34250,0.085000,0.205000,0.190000,0.150000,0.375000
std,0.322418,0.392792,0.306937,0.228266,0.482728,0.47514,0.279231,0.404207,0.392792,0.357519,0.484729
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,1.000000,0.000000,0.000000,1.000000,1.00000,0.000000,0.000000,0.000000,0.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000

In [60]:
df_clean.to_csv("Final_pre_processing_data.csv")

MODEL BUILD

In [61]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential, model_from_json  # Use model_from_json instead of model_from_yaml

from keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.layers import Dense, Dropout, LSTM, Conv1D, MaxPooling1D, Flatten
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from keras.optimizers import Adam

In [62]:
X = df_clean.drop(['id', 'classification'], axis=1)
y = df_clean['classification']

In [63]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X, y)

# Get feature importances
importances = model.feature_importances_

# Create a DataFrame for easy viewing
feature_importances = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

print(feature_importances)

   Feature  Importance
14    hemo    0.261234
15     pcv    0.150675
11      sc    0.118046
17      rc    0.082986
3       al    0.075206
2       sg    0.069719
18     htn    0.059592
10      bu    0.032620
19      dm    0.029665
9      bgr    0.029178
12     sod    0.026756
1       bp    0.011266
13     pot    0.009955
0      age    0.009233
22      pe    0.008041
16      wc    0.005864
4       su    0.005768
6       pc    0.004856
5      rbc    0.003497
23     ane    0.003243
21   appet    0.002179
7      pcc    0.000286
8       ba    0.000135
20     cad    0.000000

In [64]:
top_features = feature_importances['Feature'].head(13).tolist()
X = X[top_features]

In [65]:
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter

In [66]:
ros=RandomOverSampler()
X_ros, y_ros=ros.fit_resample(X, y)
print(Counter(y_ros))

Counter({0: 250, 1: 250})

In [67]:
scaler = MinMaxScaler(feature_range=(-1, 1))
X_scaled = scaler.fit_transform(X_ros)
y=y_ros

In [68]:
from sklearn.decomposition import PCA

In [69]:
pca=PCA(.95)
X_PCA=pca.fit_transform(X_scaled)

In [70]:
print(X.shape)
print(X_PCA.shape)

(400, 13)
(500, 7)

ANN

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X_PCA, y, test_size=0.2, random_state=42)

In [72]:
model_ann = Sequential()
model_ann.add(Dense(15, input_dim=X_train.shape[1], activation='relu'))
model_ann.add(Dropout(0.2))
model_ann.add(Dense(15, activation='relu'))
model_ann.add(Dropout(0.4))
model_ann.add(Dense(1, activation='sigmoid'))

In [73]:
model_ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [74]:
history = model_ann.fit(X_train, y_train, validation_data = (X_test, y_test), epochs = 20, verbose = 1)

Epoch 1/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - accuracy: 0.6036 - loss: 0.6689 - val_accuracy: 0.8900 - val_loss: 0.6454
Epoch 2/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6654 - loss: 0.6358 - val_accuracy: 0.9300 - val_loss: 0.6069
Epoch 3/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7244 - loss: 0.6057 - val_accuracy: 0.9500 - val_loss: 0.5668
Epoch 4/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8064 - loss: 0.5591 - val_accuracy: 0.9500 - val_loss: 0.5254
Epoch 5/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8485 - loss: 0.5402 - val_accuracy: 0.9500 - val_loss: 0.4837
Epoch 6/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9043 - loss: 0.4776 - val_accuracy: 0.9700 - val_loss: 0.4422
Epoch 7/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8851 - loss: 0.4530 - val_accuracy: 0.9700 - val_loss: 0.4009
Epoch 8/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8847 - loss: 0.4391 - val_accuracy: 0.9700 - val_loss: 0.3611
Epoch 9/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9121 - loss: 0.4028 - val_accuracy: 0.9700 - val_loss: 0.3235
Epoch 10/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9344 - loss: 0.3393 - val_accuracy: 0.9700 - val_loss: 0.2870
Epoch 11/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9077 - loss: 0.3261 - val_accuracy: 0.9700 - val_loss: 0.2551
Epoch 12/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9439 - loss: 0.2791 - val_accuracy: 0.9700 - val_loss: 0.2258
Epoch 13/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9274 - loss: 0.2719 - val_accuracy: 0.9700 - val_loss: 0.1999
Epoch 14/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9527 - loss: 0.2287 - val_accuracy: 0.9800 - val_loss: 0.1774
Epoch 15/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9489 - loss: 0.2194 - val_accuracy: 0.9800 - val_loss: 0.1585
Epoch 16/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9351 - loss: 0.2001 - val_accuracy: 0.9800 - val_loss: 0.1427
Epoch 17/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9565 - loss: 0.2099 - val_accuracy: 0.9800 - val_loss: 0.1279
Epoch 18/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9754 - loss: 0.1545 - val_accuracy: 0.9800 - val_loss: 0.1154
Epoch 19/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9637 - loss: 0.1529 - val_accuracy: 0.9800 - val_loss: 0.1046
Epoch 20/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9698 - loss: 0.1623 - val_accuracy: 0.9800 - val_loss: 0.0952

In [75]:
from sklearn.metrics import classification_report, roc_auc_score, roc_curve, precision_recall_curve, auc, f1_score,accuracy_score
from sklearn.metrics import precision_recall_curve , average_precision_score

In [76]:
y_pred_ann = (model_ann.predict(X_test) > 0.5).astype(int)

# Create a DataFrame to display the actual and predicted values
results_df = pd.DataFrame({
    'Actual': y_test.values.flatten(),
    'Predicted': y_pred_ann.flatten()
})

# Print the first few rows of the results
print("Actual vs Predicted Values:")
print(results_df.head(10))

WARNING:tensorflow:5 out of the last 9 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7c7611945e40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/4 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

WARNING:tensorflow:6 out of the last 12 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7c7611945e40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
Actual vs Predicted Values:
   Actual  Predicted
0       1          1
1       0          0
2       1          1
3       0          0
4       0          0
5       1          1
6       1          1
7       0          0
8       0          0
9       1          1

In [77]:
accuracy_ann = accuracy_score(y_test, y_pred_ann)
print("Artificial Neural Network (ANN) Accuracy Score:", accuracy_ann)

Artificial Neural Network (ANN) Accuracy Score: 0.98

CNN

In [78]:
X_cnn = X_scaled.reshape(X_scaled.shape[0], X_scaled.shape[1], 1)
X_train_cnn, X_test_cnn, y_train_cnn, y_test_cnn = train_test_split(X_cnn, y, test_size=0.2, random_state=42)

In [79]:
model_cnn = Sequential()
model_cnn.add(Conv1D(32, 3, activation='relu', input_shape=(X_train_cnn.shape[1], X_train_cnn.shape[2])))
model_cnn.add(MaxPooling1D(2))
model_cnn.add(Conv1D(64, 3, activation='relu'))
model_cnn.add(MaxPooling1D(2))
model_cnn.add(Flatten())
model_cnn.add(Dense(128, activation='relu'))
model_cnn.add(Dropout(0.5))
model_cnn.add(Dense(1, activation='sigmoid'))

In [80]:
model_cnn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [81]:
history_cnn = model_cnn.fit(X_train_cnn, y_train_cnn, epochs=30, batch_size=32, verbose=0, validation_data=(X_test_cnn, y_test_cnn))

In [82]:
y_pred_cnn = (model_cnn.predict(X_test_cnn) > 0.5).astype(int)

# Create a DataFrame to display the actual and predicted values
results_df = pd.DataFrame({
    'Actual': y_test_cnn.values.flatten(),
    'Predicted': y_pred_cnn.flatten()
})

# Print the first few rows of the results
print("Actual vs Predicted Values:")
print(results_df.head(10))

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
Actual vs Predicted Values:
   Actual  Predicted
0       1          1
1       0          0
2       1          1
3       0          0
4       0          0
5       1          1
6       1          1
7       0          0
8       0          0
9       1          1

In [83]:
accuracy_cnn = accuracy_score(y_test_cnn, y_pred_cnn)
print("Convolutional Neural Network (CNN) Model Accuracy Score:", accuracy_cnn)

Convolutional Neural Network (CNN) Model Accuracy Score: 0.99

In [84]:
import pickle

In [85]:
filename = 'kidney_model.sav'
pickle.dump(model_cnn, open(filename, 'wb'))

In [86]:
loaded_model = pickle.load(open('kidney_model.sav', 'rb'))

In [87]:
for column in X.columns:
  print(column)

hemo
pcv
sc
rc
al
sg
htn
bu
dm
bgr
sod
bp
pot